services:
  product-db:
    image: mongo:7
    container_name: product-db
    ports:
      - "27017:27017"
    volumes:
      - product-db-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

volumes:
  product-db-data:
